title: Viviene Noel
email: vivienenoel.author@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the world of Fanhalen. Hi, I'm Viviene Noel, the author of ´A Curse of Blood and Power´ series.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://vivienenoel.com # the base hostname & protocol for your site, e.g. http://example.com
domain: vivienenoel.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-email-protect

collections:
  projects: 
    output: true

social:
  - name: instagram
    url: https://www.instagram.com/vivienenoel.author/
  - name: pinterest
    url: https://www.pinterest.com/vivienenoelauthor/
  - name: tiktok
    url: https://www.tiktok.com/@viv_noel

footer: "© vivienenoel.com"

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      title: Project
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: Post
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
